language: php

sudo: false

php:
   - 7.1
   - 7.2

before_install:
    - mkdir --parents "${HOME}/bin"

install:
    - composer install

before_script:
    - wget "http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar" --output-document="${HOME}/bin/php-cs-fixer"
    - chmod u+x "${HOME}/bin/php-cs-fixer"
    - php-cs-fixer fix --diff --dry-run -v

script:
    - composer validate --strict --no-check-lock
    - phpunit --coverage-text
