language: php

sudo: false

#cache:
#    directories:
#        - $HOME/.composer/cache

env:
    global:
        - COMPOSER_INSTALL=true
        - PHPUNIT_FLAGS="-v"
        - PHPUNIT_VERSION="7.0"
        - TRAVIS_SCRIPT="phpunit"

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: TRAVIS_SCRIPT="lint" COMPOSER_INSTALL=false
        - php: 7.1
        - php: 7.2
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
        - php: nightly
    allow_failures:
        - php: nightly

before_install:
    - if [[ $COVERAGE != true ]]; then
          phpenv config-rm xdebug.ini || true;
      fi
    - if ! [ -z "$STABILITY" ]; then
          composer config minimum-stability ${STABILITY};
      fi
    - if ! [ -v "$DEPENDENCIES" ]; then
          composer require --no-update ${DEPENDENCIES};
      fi

install:
    - mkdir --parents "${HOME}/bin";
    - if [[ $TRAVIS_SCRIPT == 'lint' ]]; then
          wget "http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar" --output-document="${HOME}/bin/php-cs-fixer";
          chmod u+x "${HOME}/bin/php-cs-fixer";
      fi
    - if [[ $TRAVIS_SCRIPT == 'phpunit' ]]; then
          wget "https://phar.phpunit.de/phpunit-${PHPUNIT_VERSION}.phar" --output-document="${HOME}/bin/phpunit";
          chmod u+x "${HOME}/bin/phpunit";
      fi
    - if [[ $COMPOSER_INSTALL == true ]]; then
          composer validate --strict --no-check-lock;
          composer install;
      fi

script:
    - if [[ $TRAVIS_SCRIPT == 'lint' ]]; then
          php-cs-fixer fix --diff --dry-run -v;
      fi
    - if [[ $TRAVIS_SCRIPT == 'phpunit' ]]; then
          phpunit $PHPUNIT_FLAGS;
      fi
