<?php

/**
 * FS stream wrapper interface.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
declare(strict_types=1);

namespace Covex\Stream;

/**
 * @author Andrey F. Mindubaev <covex.mobile@gmail.com>
 */
interface FileSystemInterface
{
    /**
     * Constructs a new stream wrapper.
     *
     * Called when opening the stream wrapper,
     * right before stream::stream_open().
     *
     * @see http://www.php.net/manual/en/streamwrapper.construct.php
     */
    public function __construct();

    /**
     * Retrieve information about a file.
     *
     * @param string $url   Url
     * @param int    $flags Flags
     *
     * @return array|bool
     */
    public function url_stat(string $url, int $flags);

    /**
     * Create a directory.
     *
     * This method is called in response to mkdir().
     *
     * @param string $path    Path
     * @param int    $mode    Mode
     * @param int    $options Options
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.mkdir.php
     */
    public function mkdir(string $path, int $mode, int $options): bool;

    /**
     * Removes a directory.
     *
     * This method is called in response to rmdir().
     *
     * @param string $path    Path
     * @param int    $options Options
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.rmdir.php
     */
    public function rmdir(string $path, int $options): bool;

    /**
     * Delete a file.
     *
     * This method is called in response to unlink().
     *
     * @param string $path Path
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.unlink.php
     */
    public function unlink(string $path): bool;

    /**
     * Renames a file or directory.
     *
     * @param string $pathFrom Path from
     * @param string $pathTo   Path to
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.rename.php
     */
    public function rename(string $pathFrom, string $pathTo): bool;

    /**
     * Open directory handle.
     *
     * This method is called in response to opendir().
     *
     * @param string $path Path
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.dir-opendir.php
     */
    public function dir_opendir(string $path): bool;

    /**
     * Read entry from directory handle.
     *
     * This method is called in response to readdir().
     *
     * @return string|bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.dir-readdir.php
     */
    public function dir_readdir();

    /**
     * Close directory handle.
     *
     * This method is called in response to closedir().
     * Any resources which were locked, or allocated, during opening and use of
     * the directory stream should be released.
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.dir-closedir.php
     */
    public function dir_closedir(): bool;

    /**
     * Rewind directory handle.
     *
     * This method is called in response to rewinddir().
     *
     * Should reset the output generated by stream::dir_readdir().
     * i.e.: The next call to stream::dir_readdir() should
     * return the first entry in the location returned by stream::dir_opendir().
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.dir-rewinddir.php
     */
    public function dir_rewinddir(): bool;

    /**
     * Opens file or URL.
     *
     * This method is called immediately after the wrapper is initialized
     * (f.e. by fopen() and file_get_contents()).
     *
     * @param string $path        Path
     * @param string $mode        Mode
     * @param int    $options     Options
     * @param string &$openedPath Opened Path
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-open.php
     */
    public function stream_open(string $path, string $mode, int $options, ?string &$openedPath): bool;

    /**
     * Close an resource.
     *
     * This method is called in response to fclose().
     *
     * All resources that were locked, or allocated, by the wrapper
     * should be released.
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-close.php
     */
    public function stream_close(): void;

    /**
     * Retrieve information about a file resource.
     *
     * This method is called in response to fstat().
     *
     * @return array
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-stat.php
     */
    public function stream_stat(): array;

    /**
     * Read from stream.
     *
     * This method is called in response to fread() and fgets().
     *
     * @param int $count Count
     *
     * @return string
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-read.php
     */
    public function stream_read(int $count): string;

    /**
     * Tests for end-of-file on a file pointer.
     *
     * This method is called in response to feof().
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-eof.php
     *
     * @return bool
     */
    public function stream_eof(): bool;

    /**
     * Retrieve the current position of a stream.
     *
     * This method is called in response to ftell().
     *
     * @return int
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-tell.php
     */
    public function stream_tell(): int;

    /**
     * Seeks to specific location in a stream.
     *
     * This method is called in response to fseek().
     *
     * The read/write position of the stream should be updated according to
     * the offset and whence.
     *
     * @param int $offset Offset
     * @param int $whence = SEEK_SET
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-seek.php
     */
    public function stream_seek(int $offset, int $whence = SEEK_SET): bool;

    /**
     * Write to stream.
     *
     * This method is called in response to fwrite().
     *
     * @param string $data Data
     *
     * @return int
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-write.php
     */
    public function stream_write(string $data): int;

    /**
     * Flushes the output.
     *
     * This method is called in response to fflush().
     *
     * If you have cached data in your stream but not yet stored it into the
     * underlying storage, you should do so now.
     *
     * @return bool
     *
     * @see http://www.php.net/manual/en/streamwrapper.stream-flush.php
     */
    public function stream_flush(): bool;
}
